### ISSUE TITLE
Some really long test failure stacktraces are cut

### ISSUE THREAD

**Issue by priomino** [KasperskyLab/Kaspresso#220] opened 2020-11-26 10:55 UTC
Some times stacktraces are really long, and it allmost impossible to guess where problem occurs

**Comment by matzuk** [comment] 2020-11-30 14:52
Hi!
Your description is too short to understand and estimate the problem. Can you reveal the details?

**Comment by priomino** [comment] 2020-12-02 11:23
For example, if you have 
- large step 
- waiting for some element
- there are many elements on screen

you will receive exception like this:
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: ********)

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1080, height=1920, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(fillxfill) ty=1 fl=#81810100 pfl=0x20000 wanim=0x1030465 needsMenuKey=2}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=3}
|
........
+->View{id=16908335, res-name=statusBarBackground, visibility=VISIBLE, width=1080, height=63, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@4bc5d3a, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}
|
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1566)
at com.kaspersky.kaspresso.failure.FailureLoggingProviderImpl.describedWith(FailureLogg

as you can see stack trace is cutted and will force you to reserch which operation causes this.

With this fix you can easily find full error stack trace and save time.

**Comment by matzuk** [comment] 2021-02-01 12:22
Had a conversation with @priomino. 
The resolution: the root cause is at another point in inner infrastructure.
Close this issue after an agreement with @priomino.

**Closed by matzuk** 2021-02-01 12:22 UTC
