### ISSUE TITLE
device.keyboard.typeText for russian characters

### ISSUE THREAD

**Issue by qwert2603** [KasperskyLab/Kaspresso#50] opened 2019-11-19 08:50 UTC
`device.keyboard.typeText("йцуке")`
throws
`com.kaspersky.kaspresso.internal.exceptions.AdbServerException: command=input text й was performed with failed result=CommandResult(status=FAILED, description=exitCode=137, message=)`

tested with:
* kaspresso 1.0.1
* emulator Pixel 2 API 25.

**Comment by RuslanMingaliev** [comment] 2020-05-10 14:56
Hi there!
`device.keyboard.typeText(...)` uses adb commands for typing char by char. Unfortunately, it does not support cyrillic characters. 

Please, consider to use `ViewActions#typeText` with Espresso or `UiObject#setText`with UiAutomator. Also, you can use Kautomator's `UiViewActions` for the same purpose.

**Comment by RuslanMingaliev** [comment] 2020-05-10 14:58
@qwert2603 I'm closing the issue. Please, reopen it if the issue is still actual.

**Closed by RuslanMingaliev** 2020-05-10 14:58 UTC
Labels: bug

**Comment by qwert2603** [comment] 2020-05-11 08:11
@RuslanMingaliev Hi! OK, thank you for response.
